databases:
  - name: taskbloomdb
    plan: free
    databaseName: taskbloom
    user: taskbloom

services:
  - type: web
    plan: free
    name: taskbloom
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn task-management-system.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: taskbloomdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
